GET http://localhost:3000/api/business/test
Content-Type: application/json

{
    "name": "Oyaji Sushi",
    "address1": "10341 Yonge Street",
    "city": "Richmond Hill",
    "state": "ON",
    "country": "CA"
}